apiVersion: v1
kind: Service
metadata:
  name: my-backend-nodeport

spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 31100

  selector:
    app: myapp
    type: backend
