apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend-deployment
  labels:
    app: myapp
    type: frontend

spec:
  template:
    metadata:
      name: my-frontend-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: my-frontend-container
          image: project/myfrontend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      type: frontend
