apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local-dev
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"
