apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "keycloak-development"
spec:
  selector:
    matchLabels:
      app: "keycloak-development"
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "keycloak-development"
    spec:
      containers:
        - name: "keycloak-development"
          image: "quay.io/keycloak/keycloak:16.0.0"
          imagePullPolicy: "Always"
          env:
            - name: "KEYCLOAK_USER"
              value: "admin"

            - name: "KEYCLOAK_PASSWORD"
              value: "admin"

            - name: "PROXY_ADDRESS_FORWARDING"
              value: "true"
            - name: "KEYCLOAK_FRONTEND_URL"
              value: "https://mykeycloak-development/"

            - name: "KEYCLOAK_ADMIN_URL"
              value: "https://mkeycloak-development/realms/"

          ports:
            - name: "http"
              containerPort: 8080
            - name: "https"
              containerPort: 8443
